frr defaults traditional
hostname server
service integrated-vtysh-config
!
interface lo
 ip address 192.168.0.2/32
!
interface eth2
 ip address 10.0.2.2/30
!
interface eth4
 ip address 10.0.4.2/30
!
router bgp 65002
 bgp router-id 192.168.0.2
 no bgp ebgp-requires-policy
 neighbor 10.0.2.1 remote-as 65010
 neighbor 10.0.4.1 remote-as 65020
 !
 address-family ipv4 unicast
  network 192.168.0.2/32
 exit-address-family
!
ip prefix-list CLIENT-LOOPBACK seq 10 permit 192.168.0.1/32
!
route-map BGP-PREFERRED-SOURCE permit 10
 match ip address prefix-list CLIENT-LOOPBACK
 set src 192.168.0.2
!
ip protocol bgp route-map BGP-PREFERRED-SOURCE
!
line vty
!